package com.simplerishta.cms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ApplicationConfigurationsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicationConfigurationsAllPropertiesEquals(
        ApplicationConfigurations expected,
        ApplicationConfigurations actual
    ) {
        assertApplicationConfigurationsAutoGeneratedPropertiesEquals(expected, actual);
        assertApplicationConfigurationsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicationConfigurationsAllUpdatablePropertiesEquals(
        ApplicationConfigurations expected,
        ApplicationConfigurations actual
    ) {
        assertApplicationConfigurationsUpdatableFieldsEquals(expected, actual);
        assertApplicationConfigurationsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicationConfigurationsAutoGeneratedPropertiesEquals(
        ApplicationConfigurations expected,
        ApplicationConfigurations actual
    ) {
        assertThat(expected)
            .as("Verify ApplicationConfigurations auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicationConfigurationsUpdatableFieldsEquals(
        ApplicationConfigurations expected,
        ApplicationConfigurations actual
    ) {
        assertThat(expected)
            .as("Verify ApplicationConfigurations relevant properties")
            .satisfies(e -> assertThat(e.getConfigKey()).as("check configKey").isEqualTo(actual.getConfigKey()))
            .satisfies(e -> assertThat(e.getConfigValue()).as("check configValue").isEqualTo(actual.getConfigValue()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getCountryCode()).as("check countryCode").isEqualTo(actual.getCountryCode()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicationConfigurationsUpdatableRelationshipsEquals(
        ApplicationConfigurations expected,
        ApplicationConfigurations actual
    ) {
        // empty method
    }
}
